[package]
name = "firere/roact-spring"
description = "A modern spring-physics based animation library for Roact inspired by react-spring"
version = "1.1.3"
license = "MIT"
authors = ["chriscerie", "firere"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^4.0"
TestEZ = "roblox/testez@^0.4"
React = "firere/roact@^1"